// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE chat_id = $1 AND user_id = $2
`

type DeleteConversationParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) DeleteConversation(ctx context.Context, db DBTX, arg DeleteConversationParams) error {
	_, err := db.ExecContext(ctx, deleteConversation, arg.ChatID, arg.UserID)
	return err
}

const deleteDurableUpdate = `-- name: DeleteDurableUpdate :exec
DELETE FROM durable_updates WHERE session_id = $1 AND id = $2
`

type DeleteDurableUpdateParams struct {
	SessionID string
	ID        string
}

func (q *Queries) DeleteDurableUpdate(ctx context.Context, db DBTX, arg DeleteDurableUpdateParams) error {
	_, err := db.ExecContext(ctx, deleteDurableUpdate, arg.SessionID, arg.ID)
	return err
}

const deletePeer = `-- name: DeletePeer :exec
DELETE FROM peers WHERE id = $1
`

func (q *Queries) DeletePeer(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, deletePeer, id)
	return err
}

const existsDedupKey = `-- name: ExistsDedupKey :one
SELECT COUNT(*) FROM update_dedup WHERE session_id = $1 AND dedup_key = $2
`

type ExistsDedupKeyParams struct {
	SessionID string
	DedupKey  string
}

func (q *Queries) ExistsDedupKey(ctx context.Context, db DBTX, arg ExistsDedupKeyParams) (int64, error) {
	row := db.QueryRowContext(ctx, existsDedupKey, arg.SessionID, arg.DedupKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChannelUpdateState = `-- name: GetChannelUpdateState :one
SELECT session_id, channel_id, pts
FROM channel_update_state
WHERE session_id = $1 AND channel_id = $2
`

type GetChannelUpdateStateParams struct {
	SessionID string
	ChannelID int64
}

type GetChannelUpdateStateRow struct {
	SessionID string
	ChannelID int64
	Pts       int32
}

func (q *Queries) GetChannelUpdateState(ctx context.Context, db DBTX, arg GetChannelUpdateStateParams) (GetChannelUpdateStateRow, error) {
	row := db.QueryRowContext(ctx, getChannelUpdateState, arg.SessionID, arg.ChannelID)
	var i GetChannelUpdateStateRow
	err := row.Scan(&i.SessionID, &i.ChannelID, &i.Pts)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT chat_id, user_id, name, step, data, created_at, updated_at
FROM conversations
WHERE chat_id = $1 AND user_id = $2
`

type GetConversationParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) GetConversation(ctx context.Context, db DBTX, arg GetConversationParams) (Conversation, error) {
	row := db.QueryRowContext(ctx, getConversation, arg.ChatID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.Name,
		&i.Step,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeer = `-- name: GetPeer :one
SELECT id, type, access_hash, username, usernames, first_name, last_name, phone_number, is_bot, photo_id, language, last_updated
FROM peers
WHERE id = $1
`

func (q *Queries) GetPeer(ctx context.Context, db DBTX, id int64) (Peer, error) {
	row := db.QueryRowContext(ctx, getPeer, id)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccessHash,
		&i.Username,
		&i.Usernames,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.IsBot,
		&i.PhotoID,
		&i.Language,
		&i.LastUpdated,
	)
	return i, err
}

const getPeerByUsername = `-- name: GetPeerByUsername :one
SELECT id, type, access_hash, username, usernames, first_name, last_name, phone_number, is_bot, photo_id, language, last_updated
FROM peers
WHERE username = $1
`

func (q *Queries) GetPeerByUsername(ctx context.Context, db DBTX, username string) (Peer, error) {
	row := db.QueryRowContext(ctx, getPeerByUsername, username)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccessHash,
		&i.Username,
		&i.Usernames,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.IsBot,
		&i.PhotoID,
		&i.Language,
		&i.LastUpdated,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT session_id, dc_id, api_id, api_hash, test_mode, auth_key, state, user_id, is_bot, first_name, last_name, username, date, server_address, port
FROM sessions
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, db DBTX) (Session, error) {
	row := db.QueryRowContext(ctx, getSession)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.DcID,
		&i.ApiID,
		&i.ApiHash,
		&i.TestMode,
		&i.AuthKey,
		&i.State,
		&i.UserID,
		&i.IsBot,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Date,
		&i.ServerAddress,
		&i.Port,
	)
	return i, err
}

const getUpdateState = `-- name: GetUpdateState :one
SELECT session_id, pts, qts, date, seq
FROM update_state
WHERE session_id = $1
`

type GetUpdateStateRow struct {
	SessionID string
	Pts       int32
	Qts       int32
	Date      int32
	Seq       int32
}

func (q *Queries) GetUpdateState(ctx context.Context, db DBTX, sessionID string) (GetUpdateStateRow, error) {
	row := db.QueryRowContext(ctx, getUpdateState, sessionID)
	var i GetUpdateStateRow
	err := row.Scan(
		&i.SessionID,
		&i.Pts,
		&i.Qts,
		&i.Date,
		&i.Seq,
	)
	return i, err
}

const insertDedupKey = `-- name: InsertDedupKey :execrows
INSERT INTO update_dedup (session_id, dedup_key, created_at) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertDedupKeyParams struct {
	SessionID string
	DedupKey  string
	CreatedAt int64
}

func (q *Queries) InsertDedupKey(ctx context.Context, db DBTX, arg InsertDedupKeyParams) (int64, error) {
	result, err := db.ExecContext(ctx, insertDedupKey, arg.SessionID, arg.DedupKey, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listChannelUpdateStates = `-- name: ListChannelUpdateStates :many
SELECT session_id, channel_id, pts
FROM channel_update_state
WHERE session_id = $1
`

type ListChannelUpdateStatesRow struct {
	SessionID string
	ChannelID int64
	Pts       int32
}

func (q *Queries) ListChannelUpdateStates(ctx context.Context, db DBTX, sessionID string) ([]ListChannelUpdateStatesRow, error) {
	rows, err := db.QueryContext(ctx, listChannelUpdateStates, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelUpdateStatesRow{}
	for rows.Next() {
		var i ListChannelUpdateStatesRow
		if err := rows.Scan(&i.SessionID, &i.ChannelID, &i.Pts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDurableUpdates = `-- name: ListDurableUpdates :many
SELECT session_id, id, payload, attempts, last_error, created_at, updated_at
FROM durable_updates
WHERE session_id = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListDurableUpdatesParams struct {
	SessionID string
	Limit     int32
}

func (q *Queries) ListDurableUpdates(ctx context.Context, db DBTX, arg ListDurableUpdatesParams) ([]DurableUpdate, error) {
	rows, err := db.QueryContext(ctx, listDurableUpdates, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DurableUpdate{}
	for rows.Next() {
		var i DurableUpdate
		if err := rows.Scan(
			&i.SessionID,
			&i.ID,
			&i.Payload,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeers = `-- name: ListPeers :many
SELECT id, type, access_hash, username, usernames, first_name, last_name, phone_number, is_bot, photo_id, language, last_updated
FROM peers
`

func (q *Queries) ListPeers(ctx context.Context, db DBTX) ([]Peer, error) {
	rows, err := db.QueryContext(ctx, listPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Peer{}
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AccessHash,
			&i.Username,
			&i.Usernames,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.IsBot,
			&i.PhotoID,
			&i.Language,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDurableUpdateFailed = `-- name: MarkDurableUpdateFailed :exec
UPDATE durable_updates SET attempts = $1, last_error = $2, updated_at = $3 WHERE session_id = $4 AND id = $5
`

type MarkDurableUpdateFailedParams struct {
	Attempts  int32
	LastError string
	UpdatedAt int64
	SessionID string
	ID        string
}

func (q *Queries) MarkDurableUpdateFailed(ctx context.Context, db DBTX, arg MarkDurableUpdateFailedParams) error {
	_, err := db.ExecContext(ctx, markDurableUpdateFailed,
		arg.Attempts,
		arg.LastError,
		arg.UpdatedAt,
		arg.SessionID,
		arg.ID,
	)
	return err
}

const upsertChannelUpdateState = `-- name: UpsertChannelUpdateState :exec
INSERT INTO channel_update_state (session_id, channel_id, pts, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (session_id, channel_id) DO UPDATE SET
    pts = EXCLUDED.pts, updated_at = EXCLUDED.updated_at
`

type UpsertChannelUpdateStateParams struct {
	SessionID string
	ChannelID int64
	Pts       int32
	UpdatedAt int64
}

func (q *Queries) UpsertChannelUpdateState(ctx context.Context, db DBTX, arg UpsertChannelUpdateStateParams) error {
	_, err := db.ExecContext(ctx, upsertChannelUpdateState,
		arg.SessionID,
		arg.ChannelID,
		arg.Pts,
		arg.UpdatedAt,
	)
	return err
}

const upsertConversation = `-- name: UpsertConversation :exec
INSERT INTO conversations (chat_id, user_id, name, step, data, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (chat_id, user_id) DO UPDATE SET
    name = EXCLUDED.name, step = EXCLUDED.step, data = EXCLUDED.data,
    created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at
`

type UpsertConversationParams struct {
	ChatID    int64
	UserID    int64
	Name      string
	Step      int32
	Data      []byte
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpsertConversation(ctx context.Context, db DBTX, arg UpsertConversationParams) error {
	_, err := db.ExecContext(ctx, upsertConversation,
		arg.ChatID,
		arg.UserID,
		arg.Name,
		arg.Step,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertDurableUpdate = `-- name: UpsertDurableUpdate :exec
INSERT INTO durable_updates (session_id, id, payload, attempts, last_error, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (session_id, id) DO UPDATE SET
    payload = EXCLUDED.payload, attempts = EXCLUDED.attempts,
    last_error = EXCLUDED.last_error, updated_at = EXCLUDED.updated_at
`

type UpsertDurableUpdateParams struct {
	SessionID string
	ID        string
	Payload   []byte
	Attempts  int32
	LastError string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpsertDurableUpdate(ctx context.Context, db DBTX, arg UpsertDurableUpdateParams) error {
	_, err := db.ExecContext(ctx, upsertDurableUpdate,
		arg.SessionID,
		arg.ID,
		arg.Payload,
		arg.Attempts,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertPeer = `-- name: UpsertPeer :exec
INSERT INTO peers (id, type, access_hash, username, usernames, first_name, last_name, phone_number, is_bot, photo_id, language, last_updated)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, access_hash = EXCLUDED.access_hash, username = EXCLUDED.username,
    usernames = EXCLUDED.usernames, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name,
    phone_number = EXCLUDED.phone_number, is_bot = EXCLUDED.is_bot, photo_id = EXCLUDED.photo_id,
    language = EXCLUDED.language, last_updated = EXCLUDED.last_updated
`

type UpsertPeerParams struct {
	ID          int64
	Type        int32
	AccessHash  int64
	Username    string
	Usernames   string
	FirstName   string
	LastName    string
	PhoneNumber string
	IsBot       int
	PhotoID     int64
	Language    string
	LastUpdated int64
}

func (q *Queries) UpsertPeer(ctx context.Context, db DBTX, arg UpsertPeerParams) error {
	_, err := db.ExecContext(ctx, upsertPeer,
		arg.ID,
		arg.Type,
		arg.AccessHash,
		arg.Username,
		arg.Usernames,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.IsBot,
		arg.PhotoID,
		arg.Language,
		arg.LastUpdated,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (session_id, dc_id, api_id, api_hash, test_mode, auth_key, state, user_id, is_bot, first_name, last_name, username, date, server_address, port)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (dc_id) DO UPDATE SET
    api_id = EXCLUDED.api_id, api_hash = EXCLUDED.api_hash, test_mode = EXCLUDED.test_mode,
    auth_key = EXCLUDED.auth_key, state = EXCLUDED.state, user_id = EXCLUDED.user_id,
    is_bot = EXCLUDED.is_bot, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name,
    username = EXCLUDED.username, date = EXCLUDED.date, server_address = EXCLUDED.server_address,
    port = EXCLUDED.port
`

type UpsertSessionParams struct {
	SessionID     string
	DcID          int32
	ApiID         int32
	ApiHash       string
	TestMode      int
	AuthKey       []byte
	State         []byte
	UserID        int64
	IsBot         int
	FirstName     string
	LastName      string
	Username      string
	Date          int32
	ServerAddress string
	Port          int32
}

func (q *Queries) UpsertSession(ctx context.Context, db DBTX, arg UpsertSessionParams) error {
	_, err := db.ExecContext(ctx, upsertSession,
		arg.SessionID,
		arg.DcID,
		arg.ApiID,
		arg.ApiHash,
		arg.TestMode,
		arg.AuthKey,
		arg.State,
		arg.UserID,
		arg.IsBot,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Date,
		arg.ServerAddress,
		arg.Port,
	)
	return err
}

const upsertUpdateState = `-- name: UpsertUpdateState :exec
INSERT INTO update_state (session_id, pts, qts, date, seq, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (session_id) DO UPDATE SET
    pts = EXCLUDED.pts, qts = EXCLUDED.qts, date = EXCLUDED.date,
    seq = EXCLUDED.seq, updated_at = EXCLUDED.updated_at
`

type UpsertUpdateStateParams struct {
	SessionID string
	Pts       int32
	Qts       int32
	Date      int32
	Seq       int32
	UpdatedAt int64
}

func (q *Queries) UpsertUpdateState(ctx context.Context, db DBTX, arg UpsertUpdateStateParams) error {
	_, err := db.ExecContext(ctx, upsertUpdateState,
		arg.SessionID,
		arg.Pts,
		arg.Qts,
		arg.Date,
		arg.Seq,
		arg.UpdatedAt,
	)
	return err
}
