// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

type ChannelUpdateState struct {
	SessionID string
	ChannelID int64
	Pts       int32
	UpdatedAt int64
}

type Conversation struct {
	ChatID    int64
	UserID    int64
	Name      string
	Step      int32
	Data      []byte
	CreatedAt int64
	UpdatedAt int64
}

type DurableUpdate struct {
	SessionID string
	ID        string
	Payload   []byte
	Attempts  int32
	LastError string
	CreatedAt int64
	UpdatedAt int64
}

type Peer struct {
	ID          int64
	Type        int32
	AccessHash  int64
	Username    string
	Usernames   string
	FirstName   string
	LastName    string
	PhoneNumber string
	IsBot       int
	PhotoID     int64
	Language    string
	LastUpdated int64
}

type Session struct {
	SessionID     string
	DcID          int32
	ApiID         int32
	ApiHash       string
	TestMode      int
	AuthKey       []byte
	State         []byte
	UserID        int64
	IsBot         int
	FirstName     string
	LastName      string
	Username      string
	Date          int32
	ServerAddress string
	Port          int32
}

type UpdateDedup struct {
	SessionID string
	DedupKey  string
	CreatedAt int64
}

type UpdateState struct {
	SessionID string
	Pts       int32
	Qts       int32
	Date      int32
	Seq       int32
	UpdatedAt int64
}
